benchmark_root: /nethome/chuang475/testnvme/projects/SafeManip/libero/libero/libero
bddl_files: /nethome/chuang475/testnvme/projects/SafeManip/libero/libero/libero/bddl_files
init_states: /nethome/chuang475/testnvme/projects/SafeManip/libero/libero/libero/init_files
datasets: /srv/datasets/libero
assets: /nethome/chuang475/testnvme/projects/SafeManip/libero/libero/libero/assets
