benchmark_root: eval/simulators/libero/libero/libero
bddl_files: eval/simulators/libero/libero/libero/bddl_files
init_states: eval/simulators/libero/libero/libero/init_files
datasets: eval/simulators/libero/libero/libero/../datasets
assets: eval/simulators/libero/libero/libero/assets
